### ISSUE TITLE
Attribute names that shadow Cedar keywords are rendered in the keyword's color instead of an attribute

### ISSUE THREAD

**Issue by micahhausler** [cedar-policy/prism-cedar#18]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/prism-cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/prism-cedar/blob/main/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Syntax Highlighting features

### Describe the bug

A resource with an attribute name that shadows any Cedar keyword is rendered as the keyword's color.

### Expected behavior

Attribute text color should be applied to attribute names, even if they shadow keywords

### Reproduction steps

Add the following fields to the User entity in the Playground's PhotoApp schema
```
"principal": {"type": "String"},
"action": {"type": "String"},
"resource": {"type": "String"},
"permit": {"type": "Boolean"},
"forbid": {"type": "Boolean"},
"when": {"type": "String"},
"unless": {"type": "String"},
```

Then write the following policy:
```
permit (
    principal is PhotoApp::User,
    action == PhotoApp::Action::"viewPhoto",
    resource == PhotoApp::Photo::"vacationPhoto.jpg"
) when {
    principal.principal == "some_string" &&
    principal.action == "some_string" &&
    principal.resource == "some_string" &&
    principal.permit == true &&
    principal.forbid == false &&
    principal.when == "some_string" &&
    principal.unless == "some_string" &&
    principal.userId == "user_id"
};
```
and the `principal`/`action`/`resource`/`forbid`/`permit`/`when`/`unless` attribute accessors will be colored with the keyword colors, but `userId` will not be.
<img width="541" alt="Screenshot 2024-11-06 at 8 57 36 AM" src="https://github.com/user-attachments/assets/3396bb53-a6f1-4dc8-ab59-fe837c2ad493">

### Code Snippet

N/A

### Log output

N/A

### Additional configuration

When I tried adding the attribute `"true": {"type": "Boolean"},` to the User entity, schema validation passed, but policy syntax errored with the message:
```
this identifier is reserved and cannot be used: `true`
```

This was also the case for other reserved keywords.

**Comment by hakanson** [comment]
Where are you testing that / which version of `prism-cedar.js` are you using?

```javascript
  keyword: /\b(?<!\.)(?:permit|forbid|when|unless)\b/,
  // don't worry about excluding . before boolean reserved identifiers
  boolean: /\b(?:false|true)\b/,
  variable: /\b(?<![\.\?])(?:principal|action|resource|context)\b/,
```

I have checks for leading `.` in regex and `test/data/identifier.cedar` has coverage.  I added your test case locally, and it looks fine.

![Screen Shot 2024-11-06 at 09 11 52 AM](https://github.com/user-attachments/assets/ce5fea9b-8caf-49a9-9e0a-798e7fcfd529)

**Comment by hakanson** [comment]
Also, if you are referring to https://www.cedarpolicy.com/en/playground - there is nice "Copy inputs as shareable link" feature.  That might be using a different syntax highlighting library.

**Comment by micahhausler** [comment]
Since the playground is using an ACE editor, it seems to be different than this. Closing as this is not a prism-cedar issue
